const offerLink = "vnd.youtube://youtube.com/redirect?event=comments&redir_token=QUFFLUhqbHZfb01wQXp6LVBQODdBNzBFN3ZkQnVZaWlld3xBQ3Jtc0tsaU9ucHFsTldOMzdHNmRtSEllMG9TOVlwTFBfOURjOHZDX0FydENsQWVST0U4ZzhoWXRZTnFVa3RSdTNGeHRqZHpYOGE0anhpTndoNzlrMjd0ZkpYRmdLM19FeW9WVjBPQ1ljTndEYWlUT3BfLXZLZw&q=https%3A%2F%2Fcuty.io%2FPGgj0&html_redirect=1 ";




